spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cartdb
    username: cart_admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
